"""
Trade signal data structures.
Represents trading decisions made by the strategy engine.
"""
from dataclasses import dataclass
from typing import Literal


@dataclass
class TradeSignal:
    """
    Represents a trading signal generated by the strategy engine.
    
    Attributes:
        side: "YES" or "NO" - which side to buy
        price: Price limit in ticks (0-1000)
        size: Number of shares to buy
        reason: Human-readable reason for the signal (for logging/debugging)
        priority: Priority level (0-3) that triggered this signal
    """
    side: Literal["YES", "NO"]
    price: float  # Price in ticks (0-1000)
    size: float   # Number of shares
    reason: str   # Human-readable reason
    priority: int  # 0-3: 0=Synthetic Arbitrage, 1=Oracle Filter, 2=Inventory, 3=Bailout
    
    def __post_init__(self):
        """Validate signal data."""
        if self.side not in ["YES", "NO"]:
            raise ValueError(f"Invalid side: {self.side}")
        if not (0 <= self.price <= 1000):
            raise ValueError(f"Price must be between 0 and 1000, got {self.price}")
        if self.size <= 0:
            raise ValueError(f"Size must be positive, got {self.size}")
        if not (0 <= self.priority <= 3):
            raise ValueError(f"Priority must be between 0 and 3, got {self.priority}")

